### PR TITLE
Add Debian 11

### PR DESCRIPTION
**Pull request by mikeday**

### CODE REVIEW

**Comment by alfiedotwtf** [comment]
Looks good. Have you built this and run the tests locally?

Otherwise, I'm happy to do it

**Comment by mikeday** [comment]
Thanks if you could run the tests that would be helpful!

**Comment by alfiedotwtf** [comment]
Sure, I'll do that now.

**Comment by alfiedotwtf** [comment]
LGTM.

Sorry, I read this as `prince-docker` rather than `docker-prince`, so there are no tests, but my test run by hand looks good.

**Pull request merged**
